# Generated by Django 5.1.6 on 2025-03-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='devuelto',
            field=models.BooleanField(default=False),
        ),
    ]
